account/urls.py
from django.urls import path, include
# from .views import *
from . import views

app_name = 'account'

urlpatterns = [
    path('logout/', views.logout , name = 'logout'),
    path('login/', views.login , name = 'login'),
    path('register/', views.register, name = 'register'),
]

board/urls.py
from django.urls import path
from .views import *

app_name = 'board'

urlpatterns = [
    path('board_list', board_list, name = 'board_list'),
]

emsysweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('board/', include('board.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.mainpage, name = 'mainpage')
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class EmsysUserManager(BaseUserManager):
    def create_user(self, username, name, department, student_number, gender, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username field must be set')
        if not name:
            raise ValueError('The Name field must be set')
        if not department:
            raise ValueError('The Department field must be set')
        if not student_number:
            raise ValueError('The Student Number field must be set')
        if not gender:
            raise ValueError('The Gender field must be set')

        user = self.model(
            username=username,
            name=name,
            department=department,
            student_number=student_number,
            gender=gender,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, name, department, student_number, gender, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(
            username=username,
            name=name,
            department=department,
            student_number=student_number,
            gender=gender,
            password=password,
            **extra_fields
        )

class EmsysUser(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    
    username = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    student_number = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['name', 'department', 'student_number', 'gender']

    objects = EmsysUserManager()

    def __str__(self):
        return f'{self.username} / 이름 : {self.name} / 학번 : {self.student_number}'

board/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Board(models.Model):
    """
        title: 제목
        content: 내용
        author: 작성자
        like_count: 좋아요 카운트
        pub_date: 배포일
    """
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=500)
    author = models.CharField(max_length=100)
    like_count = models.PositiveIntegerField(default=0) # 양수입력 필드
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.title

class Reply(models.Model):
    """
        reply: Reply -> Board 연결관계
        comment: 댓글내용
        rep_date: 작성일
    """
    reply = models.ForeignKey(Board, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    rep_date = models.DateTimeField()

    def __str__(self):
        return self.comment

account/views.py
from django.shortcuts import render, redirect

def test(request):
    return redirect('main:mainpage')

def logout(request):
    return render(request, 'account/login.html')

def login(request):
    return render(request, 'account/login.html')

def register(request):
    return render(request, 'account/register.html')

board/views.py
from django.shortcuts import render, redirect

def test(request):
    return redirect('main:mainpage')

#def board_list(request):
#    return render(request, 'board/board_list.html')

def board_list(request):
    context = {
        'title': 'Board list',
        'board_list': [
            {'no':1, 'title': '목록1' },
            {'no':2, 'title': '목록2' },
            {'no':3, 'title': '목록3' },
            {'no':4, 'title': '목록4' },
            {'no':5, 'title': '목록5' }
        ]
    }
    return render(request, 'board/board_list.html', context)

main/views.py
from django.shortcuts import render

def mainpage(request):
    return render(request, 'main/mainpage.html')

templates/board/board.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<!-- 일단 기능 구현 하고 class로 묶는 건 나중에 -->
<!-- https://cha4ser.tistory.com/entry/Web-%EA%B2%8C%EC%8B%9C%ED%8C%90-%EB%A7%8C%EB%93%A4%EA%B8%B003Flask%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%9D%B4%EB%8F%99%EA%B8%80%EC%93%B0%EA%B8%B0-%ED%8E%98%EC%9D%B4%EC%A7%80 -->
<div class="container">
    <br>
    <h1 class="test-center">### 게시판</h1>
    <br>
    <table class="table table-hover table-striped text-center" style="border: 1px solid;">
        <!-- table-striped: 홀수, 짝수행 마다 색을 다르게 함 -->
        <thred>
            <tr>
                <th>번호</th>
                <th>제목</th>
                <th>글쓴이</th>
                <th>조회수</th>
            </tr>
        </thred>
        <tobody>
            <tr>
                <td>1</td>
                <td>Title_1</td>
                <td>콩</td>
                <td>1</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Title_2</td>
                <td>캥</td>
                <td>1</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Title_3</td>
                <td>이</td>
                <td>1</td>
            </tr>
        </tobody>
    </table>

    <hr>
    <div>
        <ul class="pagination justify-content-center">
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>1</li>
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>2</li>
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>3</li>
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>4</li>
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>5</li>
        </ul>
    </div>

    <a class="btn btn-outline=info flat-right">글쓰기</a>
</div>
{% endblock %}

templates/board/board_list.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<!-- 일단 기능 구현 하고 class로 묶는 건 나중에 -->
<!-- https://cha4ser.tistory.com/entry/Web-%EA%B2%8C%EC%8B%9C%ED%8C%90-%EB%A7%8C%EB%93%A4%EA%B8%B003Flask%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%9D%B4%EB%8F%99%EA%B8%80%EC%93%B0%EA%B8%B0-%ED%8E%98%EC%9D%B4%EC%A7%80 -->
<!-- url설정 같은건 다음 페이지 참고 -->
<!-- https://velog.io/@charmull/Django-%EC%97%B0%EC%8A%B5-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B2%8C%EC%8B%9C%ED%8C%90-%EB%A7%8C%EB%93%A4%EA%B8%B0-8-%ED%85%9C%ED%94%8C%EB%A6%BF-%EB%8F%99%EC%A0%81-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%84%EB%8B%AC -->
<!-- <div class="container">
    <br>
    <h1 class="test-center">### 게시판</h1>
    <br>
    <table class="table table-hover table-striped text-center" style="border: 1px solid;">
        table-striped: 홀수, 짝수행 마다 색을 다르게 함
        <thred>
            <tr>
                <th>번호</th>
                <th>제목</th>
                <th>글쓴이</th>
                <th>조회수</th>
            </tr>
        </thred>
        <tobody>
            <tr>
                <td>1</td>
                <td>Title_1</td>
                <td>콩</td>
                <td>1</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Title_2</td>
                <td>캥</td>
                <td>1</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Title_3</td>
                <td>이</td>
                <td>1</td>
            </tr>
        </tobody>
    </table>

    <hr>
    <div>
        <ul class="pagination justify-content-center">
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>1</li>
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>2</li>
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>3</li>
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>4</li>
            <li><a href="#" style="margin-right:5px;" class="text-secondary"></a>5</li>
        </ul>
    </div>

    <a class="btn btn-outline=info flat-right">글쓰기</a>
</div> -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>{{ title }}</h2>
    <br><br><br>

{% if board_list %}
    <ul>
        {% for data in board_list %}
        <li>{{ data.no }} : {{ data.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <h2>no board list</h2>
{% endif %}
</body>
</html>
{% endblock %}

templates/main/mainpage.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<div class="imgcontainer">
    <div class = 'introduce-board' id="introduceImage" style = "background-image: url('{% static 'img/letsgo.jpg' %}');"></div>
    <div class = 'introduce-board' id="introduceImage" style = "background-image: url('{% static 'img/letsgo.jpg' %}');"></div>
    
    <div class = 'main-text-box'>
        <p class = 'main-text'>
            충북대학교 학술 동아리
        </p>    
        <p class = 'main-text'>
            EMSYS
        </p>
    </div>
</div>
<div class = 'second-content'>
    <div class = 'miniboard bg-200'>
        <p class = 'miniboard-title'>
            공지사항
        </p> 
        <div class = 'miniboard-content-box bg-100'>
            <div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div>
            <div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div>
            <div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div>
            <div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div>
            <div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div>
        </div>
    </div>
    <div class = 'miniboard bg-200'>
        <p class = 'miniboard-title'>
            자유게시판
        </p> 
        <div class = 'miniboard-content-box bg-100'>
            <div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div>
            <div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div><div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div><div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div><div class = 'miniboard-item'>
                <p class = 'miniboard-content' style="width:10%;">
                    1
                </p>
                <p class = 'miniboard-content' style="width:30%; text-align:left">
                    제목
                </p>
                <p class = 'miniboard-content' style="width:20%;">
                    작성자
                </p>
                <p class = 'miniboard-content' style="width:40%">
                    YYYY-MM-DD
                </p>
            </div>
        </div>
    </div>
</div>
<script src = "{% static 'js/mainpage.js' %}"></script>
{% endblock %}

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href = "{% static 'css/colors.css' %}">
    <link rel="stylesheet" href = "{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href = "{% static 'css/main.css' %}">
    <!-- board.css 추가 -->
    <link rel="stylesheet" href = "{% static 'css/board.css' %}">
    <title>EMSYS</title>
</head>

<body class="bg-300">
    <nav class="navbar navbar-expand-lg bg-100">
        <div class="container-fluid">
            <a class = "imglink" href ="{% url 'main:mainpage' %}">
                <img class = "navbar-brand logo"  src="{% static 'img/black-emsys-logo.png'%}">
            </a>
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">소개</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:board_list' %}">게시판</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">자료실</a>
                </li>
            </ul>
            {% if user.is_autenticated %}
            <ul class="navbar-nav">
                <li class ="nav-item dropstart">
                    <a class = "nav-link dropdown-toggle" href="#" role = "button" data-bs-toggle="dropdown" aria-expanded="false">
                        황재찬
                    </a>
                    <ul class="dropdown-menu">
                        <li style="text-align: center;">
                            <a class="dropdown-item me-left" href="#">
                                마이페이지
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li style="text-align: center;">
                            <a class = "imglink" href="{% url 'account:logout' %}">
                                <img class = "icon" src = "{% static 'img/logout-icon.png' %}" >
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav">
                <li class ="nav-item">
                    <a class = "nav-link" href="{% url 'account:login' %}">로그인</a>
                </li>
                <li class ="nav-item">
                    <a class = "nav-link" href="{% url 'account:register' %}">회원가입</a>
                </li>
            </ul>
            {% endif %}
        </div>    
        
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>